name: regularized_glm
channels:
- defaults
- conda-forge
dependencies:
- "python>=3.4"
- "numpy>=1.14"
- scipy
- statsmodels
- matplotlib
- jupyter
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
